{{- if and (not .Values.aws.existingSecret) (not .Values.aws.useIRSA) .Values.aws.credentials.accessKeyId }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "statecraft.fullname" . }}-aws
  labels:
    {{- include "statecraft.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.credentials.accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.credentials.secretAccessKey | b64enc | quote }}
  AWS_DEFAULT_REGION: {{ .Values.aws.credentials.defaultRegion | default "us-east-1" | b64enc | quote }}
{{- end }}
